// Common
const THROTTLE_TTL = 1;
const THROTTLE_LIMIT = 3;

// Token
const NUMBER_OF_TOKENS_ISSUED = 5;

// User
const USERS_DEFAULT_LIMIT = 50;
const USERS_MAXIMUM_LIMIT = 200;
const USERS_DEFAULT_OFFSET = 0;

// Publication
const PUBLICATIONS_DEFAULT_LIMIT = 50;
const PUBLICATIONS_MAXIMUM_LIMIT = 200;
const PUBLICATIONS_DEFAULT_OFFSET = 0;

export {
  NUMBER_OF_TOKENS_ISSUED,
  USERS_DEFAULT_LIMIT,
  USERS_MAXIMUM_LIMIT,
  USERS_DEFAULT_OFFSET,
  THROTTLE_TTL,
  THROTTLE_LIMIT,
  PUBLICATIONS_DEFAULT_LIMIT,
  PUBLICATIONS_MAXIMUM_LIMIT,
  PUBLICATIONS_DEFAULT_OFFSET,
};
